plugins {
    id 'java'
}

allprojects {
    apply plugin: 'java'

    group = project.mod_group_id
    version = project.mod_version

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = "https://maven.createmod.net" }
        maven { url = "https://maven.ithundxr.dev/snapshots" }
        maven { url = "https://cursemaven.com" }
    }
}
