org.gradle.java.home=C:/Users/anoop/.jdks/temurin-21.0.12
# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Common Mod Properties
mod_id=transferables
mod_name=Create Transferables
mod_license=MIT
mod_version=3.0
mod_group_id=com.reggarf.mods
mod_authors=Reggarf
mod_description=Ever wanted to just stick a fluid pipe or a Create shaft straight through a Nether portal? This mod lets you do exactly that. Send your fluids and rotational power across dimensions without the headache.

## 1.21.1 NeoForge Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
java_version=21
neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
create_version=6.0.10-280
create_version_range=[6.0.10,6.1.0)
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
jei_minecraft_version=1.21.1
jei_version=19.21.0.247

## 1.20.1 Forge Properties
minecraft_version_1_20=1.20.1
minecraft_version_range_1_20=[1.20.1,1.21)
java_version_1_20=17
forge_version_1_20=47.3.0
forge_version_range_1_20=[47,)
loader_version_range_1_20=[47,)
create_version_1_20=6.0.8-289
create_version_range_1_20=[6.0.8,6.1.0)
ponder_version_1_20=1.0.91
flywheel_version_1_20=1.0.5
registrate_version_1_20=MC1.20-1.3.3

## 1.20.1 Fabric Properties
fabric_loader_version_1_20=0.17.2
fabric_api_version_1_20=0.92.6+1.20.1
parchment_version_1_20=2023.09.03
create_fabric_version_1_20=6.0.8.1+build.1744-mc1.20.1
create_fabric_version_range_1_20=>=6.0.7
